name: Pack extensions

on:
  push:
    paths-ignore:
      - README.md
  pull_request:
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    container: ubuntu:22.04

    steps:
      - uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules
      
      - name: Prepare
        run: |
          apt update
          apt install -y gnome-shell-common libpolkit-agent-1-dev libadwaita-1-dev libmutter-10-dev libadwaita-1-dev libgtk-3-dev libgtk-4-dev libgraphene-1.0-dev libgirepository1.0-dev libnm-dev libgcr-3-dev gettext

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          npm run github_action
        
      - name: Upload Extension Pack
        uses: actions/upload-artifact@v3.1.0
        with:
          name: rounded-window-corners@yilozt.shell-extension
          path: _build/
